### ISSUE TITLE
Es fehlt eine Seite zu Katzen

### ISSUE THREAD

**Issue by ginomessmer** [project-redhead/git-crash-course#8]

**Comment by HitMan1206** [comment]
Finde ich auch

**Comment by IsabellReitler** [comment]
Dann brauchen wir aber auch noch eine Seite zu Kaninchen

**Comment by Pascal798** [comment]
Und Pferde

**Comment by ginomessmer** [comment]
Ist jetzt im Master drinnen 👌

**Comment by ginomessmer** [comment]
Es fehlen aber immer noch Pferde und Kaninchen...

**Comment by d0mmi** [comment]
hab mal noch eine bessere katze hinzugefügt
